name: "📘 Documentation Improvement"
description: "Laporkan kekurangan, kesalahan, atau saran perbaikan pada dokumentasi"
title: "[Docs]: "
labels:
  - documentation
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Terima kasih sudah bantu meningkatkan kualitas dokumentasi 🙏  
        Tolong isi laporan berikut dengan jelas supaya perbaikan bisa dilakukan lebih cepat.

  - type: input
    id: doc_section
    attributes:
      label: "Bagian Dokumentasi"
      description: "Sebutkan bagian atau file dokumentasi yang ingin kamu perbaiki"
      placeholder: "Contoh: README.md / API.md / docs/setup.md"

  - type: textarea
    id: current_issue
    attributes:
      label: "Masalah atau Kekurangan Saat Ini"
      description: "Jelaskan apa yang kurang, salah, atau membingungkan di dokumentasi"
      placeholder: "Contoh: Penjelasan langkah instalasi kurang detail untuk pengguna Windows."

  - type: textarea
    id: suggestion
    attributes:
      label: "Saran Perbaikan"
      description: "Tulis saran kamu untuk memperjelas atau memperbaiki dokumentasi"
      placeholder: "Contoh: Tambahkan langkah instalasi Python di Windows dan contoh output."

  - type: dropdown
    id: priority
    attributes:
      label: "Prioritas"
      options:
        - Rendah
        - Sedang
        - Tinggi

  - type: textarea
    id: notes
    attributes:
      label: "Catatan Tambahan"
      description: "Info lain yang bisa membantu tim memperbaiki dokumentasi"
      placeholder: "Misal: dokumentasi lama di branch legacy-docs"
